language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: pbnv7rpUKNkinSW1ebwmXJQhkSgLeKpNGL7XQXlVU+yC5ByZCuU2JTx8XE6BrO17X0/1TOmf40HxBuZ6wN1Oq+2uRrjukndt9D2TrFY0Z7NlBqcmPPcBds2xD0nNCwxwjCcF3BM7I+pNBviegfWwJmjLmFu82DfiBBbBFjIrZULEDd+UfWV11Ju7y7VABjsw74RIJlSvuoX8x3E7w3vyuN9sCUc/EOF5z4GsUh2I+rcX1b62HYhstiEkarPVhSkOUoXwSysEJftiAccJedXDG46HMPTschiNaYdymdFccSmeFdc9GDGFjUaPac8pA4WlaUcILY1A9uz2bzR2uj4uSaGkzP8EZ95jH/C91z8SA3hk4YI/grxhWbFvN1LwZC+IhWqH3fh7sRlrHKUl/XPMMujNvStLEmtYwdP64TA6sRKvr8rALQeCruJPwgADL8BybAx+Cs+cm72xPet9mTib8kSacYViHXN+g2+83Ci5mTN4SAZ8ZZkvPKwD5+ZTHCl8KjFKkyIlmC+Y67YIkdjHvIUFtW7Zx3aNGtmPDYbQQEi9pNLZqoaVPFZds42dkg6QxNfrjxmdUOVQlfcLDqa6sso+EXcfGIpooWY5kFCkstGxc/v0u9ynYOQ2RRe5CJmD4WD3TS20L6etzfi2qHyCeb9omKfXh1WzESuEAQH1csU=
  app: cryptic-depths-79050
  on:
    repo: msolorio/grocery-inventory-app
